name: Minima
favicon: null
layout_spectrum: 0.761973214102909
typography_spectrum: 0.5671426556073129
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5374018833972514
  lightness: 0.055398627649992704
  saturation: 0.2804327281191945
  rhythmicContrast: 0.240214757155627
purpose: []
